name: Publish
on:
  push:
    branches:
      - "master"

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: "yarn"
          registry-url: "https://registry.npmjs.org/"

      - run: yarn install --frozen-lockfile
      - name: Run Lint and Build
        run: yarn run lint && yarn run build

      - name: Create Release Pull Request or Publish
        id: changesets
        uses: changesets/action@v1
        with:
          version: yarn version
          publish: yarn publish

        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
